### ISSUE TITLE
Bad example for `epix_slide` in `methods-epi_archive.R` (ALREADY POSTED)

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#140]
The example produces a 3rd column of what are supposed to be 3-day averages, but they are all NA's.

The reasons why it's all NA's is because it's calling a column name, `cases`, which doesn't exist in `archive_cases_dv_subset`.

**Comment by kenmawer** [comment]
Didn't realize this was already posted.

**Comment by brookslogan** [comment]
Duplicate was of https://github.com/cmu-delphi/epiprocess/issues/137.  Changing the closed status so if we only read the issue name + the closed status on the issue list it won't look like we've already addressed this.
