### ISSUE TITLE
`epix_slide` using one too few days for rolling (NOT A BUG)

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#141]
I used a number of the form of `2^n` for some nonnegative integer `n`, slid over a sum to uniquely identify which things are being added for the sum.

```
library(dplyr)
x2 <- ea$clone()$DT %>%
    filter(geo_value == "ca", version <= as.Date("2020-06-09")) %>%
    select(-percent_cli,-case_rate_7d_av) %>%
    mutate(binary = 2^(row_number()-1)) %>%
    as_epi_archive()
  
  time_values <- seq(as.Date("2020-06-01"),
                     as.Date("2020-06-09"),
                     by = "1 day")
  xx <- epix_slide(x = x2,
            f = ~ sum(.x$binary),
            n = 3,
            group_by = geo_value,
            ref_time_values = time_values,
            new_col_name = '3d_sum_binary')
})
```

This uses a 3-day sliding summation average, but the values are as follows:

```
# A tibble: 7 × 3
  geo_value time_value `3d_sum_binary`
  <chr>     <date>               <dbl>
1 ca        2020-06-02               1 [2^0]
2 ca        2020-06-03              33 [2^5+2^0]
3 ca        2020-06-04            1056 [2^10+2^5]
4 ca        2020-06-05           33792 [2^15+2^10]
5 ca        2020-06-06          294912 [2^18+2^15]
6 ca        2020-06-07         1310720 [2^20+2^18]
7 ca        2020-06-08         3145728 [2^21+2^20]
```

It is not adding more than two values even though it rolls over 3 sums. Indeed, setting `n=2` just grabs numbers that are powers of 2, and `n=1` grabs an empty tibble (rather than taking the newest version of each day).

Note, however, that `epi_slide` works properly.

**Comment by brookslogan** [comment]
The `n` behavior is "expected".  For disease surveillance data, the data set as of day `v` will not contain any data regarding day `v`; day `v` is still going on, and the very earliest that surveillance data about day `v` (in its entirety) could be published is midnight on day `v+1`.  So the data set as of day `v` will not have data (from disease surveillance sources) regarding day `v`, and might not even have any about `v-1`, `v-2`, etc.; it depends on the latency of the data source(s) involved.

**Comment by kenmawer** [comment]
Should `n=1` actually be giving an empty tibble? It's just confusing how this differs from `epi_slide` in that `n=1` would be sliding over a day, basically serving as an identity function.

**Comment by kenmawer** [comment]
I found that this is not a bug. However, some features of `epix_slide` are questionable.
