### ISSUE TITLE
Clean up `epi_slide` `f` parameter documentation 

### ISSUE THREAD

**Issue by rachlobay** [cmu-delphi/epiprocess#143]
As discussed with Logan, update the `@param` documentation for the `f` parameter in `epi_slide`. The following are the points to address:

- Instead of “If a function, `f` must take `x`, a data frame with the same column names as the original object; followed by any number of named arguments; and ending with `...`“, the proper thing may be that `f` should take `x`, `g`/`k`/`key`/`think-of-a-better-name`, and named args (dots don’t seem necessary; I think originally they were just there to absorb the unlisted `g`).
- Correct "same column names as the original object" --- we might only get the non-grouping columns here.  [This raises a separate issue.  We are feeding the user an `epi_df` via `f` that might not have the geo_value column as one might expect.  Hopefully we can get away with it, but maybe this needs to be a proper `epi_df` or just a `tibble` instead.]
- If you think it clarifies things, change “named arguments” -> “named arguments (which will be taken from `...`)“.
- Make sure that the description of `g` above matches/resembles how `?group_modify` describes such a parameter, if it makes sense.
- In the docs for the `f` being a formula case, describe `.y` in the same manner as `g`, if `.y` can indeed be used [I'm guessing that it is usable].

Originally mentioned in PR #85.

**Comment by brookslogan** [comment]
Still see remnants of the old docs somehow.
