### ISSUE TITLE
 `epix_slide` won't grab the latest version

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#153]
Related to #146, but the `ref_time_values`, which should actually be `ref_versions`, does not take in the latest version for the slide.

**Comment by brookslogan** [comment]
From call: we should just fix the latest version not being included here, and leave the renaming for a separate discussion.  #146 contained some ideas for setting a default.

**Comment by brookslogan** [comment]
Closed by #311.
