### ISSUE TITLE
First "misspecified column names" example in `epiprocess` vignette fails with the wrong error

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/epiprocess#155]
The first `Dealing with misspecified column names` example in the `epiprocess` vignette does not exhibit the intended error, failure when creating `epi_df` due to missing `geo_Value` and `time_value` columns. It actually fails (with `## Error in NextMethod(): object 'geo_value' not found`) to generate the initial dataframe and never gets to the `epi_df` creation.

The inital df should be created as a `tibble` instead, and the [`value` and `reported_date` fields](https://github.com/cmu-delphi/epiprocess/blob/e1f85048c532c9e3ef7cf6c0207bf7717dce7a33/vignettes/epiprocess.Rmd#L164-L165) should reference `state` instead of the `geo_value` field, which doesn't exist.

**Comment by dshemetov** [comment]
Closing as outdated.
