### ISSUE TITLE
Functionality to detect outliers

### ISSUE THREAD

**Issue by elray1** [cmu-delphi/epiprocess#16]
Getting conversation started about functionality to detect outliers. Not directly specified here is the idea that we'll want to hand off the actual task of outlier detection to helper functions, e.g. functions in the R package `tsoutliers`. The functions described here are just about managing the hand off of the task to those functions, collection of results, aggregation of results across multiple algorithms, and display of results.

# detect_outliers function

```{R}
#' Detect outliers in an `epi_signal`.
#'
#' @param x An `epi_signal` in which to look for outliers.
#' @param signal_names A character vector of names of signals (columns) in the
#'   `epi_signal` in which to look for outliers.
#' @param detection_methods A data frame specifying methods to use for outlier
#'   detection. Contains the following columns:
#' * `method` <str>: The name of the detection method.
#' * `method_args` <lst>: A named list of arguments that will be passed to the
#'   detection method.
#' @param combination_method A string, either "median", "mean", or "none",
#'   specifying how to combine results from different outlier detection methods
#'   for the thresholds determining whether a particular observation is classified
#'   as an outlier, as well as a replacement value for any outliers. If "none", no
#'   summarized results are calculated. Note that if the number of
#'   `detection_methods` is odd, "median" is equivalent to a majority vote for
#'   purposes of determining whether a given observation is an outlier.
#'
#' @return The input `epi_signal` `x` augmented with detected outliers.
#'
#' @export
detect_outliers = function(x, signal_names,
                           detection_methods = <some recommended default>,
                           presence_combination = "majority",
                           replacement_combination = "median") {

}
```

I'm not quite sure what the best way to represent the output is. Some considerations:

 * We will have results for each combination of `signal_name` and `detection_method`. Maybe a new list-column for each `signal` in `signal_names`, like `<signal>_outliers`? And that column contains results from all the detection methods and the combination?
 * Maybe each detection method is asked to return four things?
    1. `lower_threshold`: lower bound for outlier detection
    2. `upper_threshold`: upper bound for outlier detection
    3. `is_outlier`: boolean recording `x$signal < lower_threshold | x$signal > upper_threshold` (may not need this explicitly?)
    4. `replacement`: the method's suggested replacement for the original value
 * Some sort of data frame tracking these things from all the methods?

If a format like that is used, we'd need a utility function to convert it to the `outliers` format required by `correct_outliers`, proposed in Issue #15.

# plot_outliers function

Makes a plot (facetted by `key` and `signal`?) showing:

 * the original series
 * Optionally, the `lower_threshold` and `upper_threshold` values over time from each detection method.
 * imputed values from each method.

```{R}
#' Plot an `epi_signal` and detected outliers.
#'
#' @param x an `epi_signal` including outlier detection results, as returned by
#'  `detect_outliers`
#' @param include_thresholds <logical>: include outlier detection thresholds in
#'   the plot?
#' @param combination_only <logical>: if `TRUE`, display only combined results
#'   across all detection methods; otherwise, display results for all detection
#'   methods.
#' @param print_plot <logical>: if `TRUE`, the plot is printed
#'
#' @return invisibly, a `ggplot` object.
plot_outliers = function(x,
                         include_thresholds = FALSE,
                         combination_only = TRUE,
                         print_plot = TRUE) {

}
```

**Comment by ryantibs** [comment]
Closed via #28.
