### ISSUE TITLE
Remove default `n` value in `epi_slide`, `epix_slide`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#160]
Make sure tests, examples, and vignettes still run.

**Comment by kenmawer** [comment]
I put in a pull request that would address this issue. Issue #161 will only begin to be addressed on this pull request is approved, as it's more complicated and builds on this issue.

**Comment by brookslogan** [comment]
Closed by https://github.com/cmu-delphi/epiprocess/pull/167.
