### ISSUE TITLE
Add option in `clone` to `copy` the DT, or at least document

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#164]
Current `clone` behavior:
- `deep=FALSE` (the default) will alias the old fields
- `deep=TRUE` is basically the same for us! It's a "deep" clone, but doesn't seem to be aware of data tables.  The `DT` is left as an alias!  Unless the user provides some R6 objects or other things that `clone` is aware of for some of the other fields (very unlikely), `deep=TRUE` doesn't actually do anything different.

We should provide a way to do an actual deep clone that does use a `copy` of the `DT`.

**Comment by dshemetov** [comment]
Closing as outdated.
