### ISSUE TITLE
Vignette for supporting a user who wants to create their own `epi_df` and `epi_archive`

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#165]
This was discussed in a earlier meeting, but the details are hazy. Please add details as needed. Also, I'm not really sure as to whether this has already been posted.

Also, another thing is to consider is whether we will get a dataset outside of covidcast, as to mimic what a user might do to meet their own needs.

**Comment by dshemetov** [comment]
Closing because the description is too vague and the details are lost to time.
