### ISSUE TITLE
Validate `f` function in `epi[x]_slide`; give better feedback if doesn't take enough args

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#168]
See this example:
```
epi_slide(jhu_csse_county_level_subset, function(x) print(x))
Error in .f(.x, ...) : unused argument (list())
```
The error message isn't that informative, and seems like it might be fairly commonly encountered.  (I have trouble remembering the `g` arg despite discussing it for a while.)

We can check that `f` takes enough arguments beforehand.  I believe I have something along these lines for a different function in #102.  (See `fn_max_n_args` definition and use.)

**Comment by brookslogan** [comment]
I've hit this while trying to use `lm.fit` or `slice_min` as the computation, which may give more confusing error messages than the above.

**Comment by brookslogan** [comment]
Having checks also hit the above cases might require something more detailed than checking `fn_max_n_args`, such as requiring the number of positional args before seeing any `...` to be at least the number of mandatory arguments for the slide.  (This might require explicitly forwarding some things to `comp_one_group` that previously we forwarded via `...`, but might catch `slice_min` even though it takes more than enough args.)

**Comment by nmdefries** [comment]
> I've hit this while trying to use lm.fit or slice_min as the computation

**Comment by nmdefries** [comment]
> I've hit this while trying to use lm.fit or slice_min as the computation

Both `lm.fit` and `slice_min` take two positional args before `...`, and are successfully passed `x` and `g` by `epi_slide`. The errors

```
epi_slide(jhu_csse_county_level_subset, slice_min, before=2L)
# Error in `.f()`:
# ! Problem while computing indices.
# Caused by error in `UseMethod()`:
# ! no applicable method for 'group_keys' applied to an object of class "rlang_data_pronoun"
```

```
epi_slide(jhu_csse_county_level_subset, lm.fit, before=2L)
# Error in .f(.x, ...) : incompatible dimensions
```

both come from internal arg validation by the provided function, so this behavior seems correct. (Also, since both functions already take 2 args before `...` the approach proposed above wouldn't catch them; we could check arg names?)

**Comment by nmdefries** [comment]
Closed in https://github.com/cmu-delphi/epiprocess/pull/302
