### ISSUE TITLE
Add way to refer to `ref_time_value` within `f` arg to `epi_slide`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#171]
See [this Slack thread](https://delphi-org.slack.com/archives/C028AUR6MV1/p1657155806592059?thread_ts=1656689163.956039&cid=C028AUR6MV1).  See #165 for `epix_slide`-related discussion.  Interacts with https://github.com/cmu-delphi/epiprocess/issues/161.

Within `f`, we'd like to refer to the `ref_time_value` we're performing the computation on.
- The workaround suggested [in the slider docs](https://davisvaughan.github.io/slider/reference/slide_index.html#examples) doesn't quite seem to be this exactly, but rather seems to be about attaching the ref_time_value to each computation after the fact.
- It might be possible to calculate the `ref_time_value` from the available `time_value`s in a time window + the `align` arg.  However, we have to worry about gaps in the `time_value`s and behavior near / at / beyond the edges of the range of `time_value`s available.  If it's possible, we could:
  - provide this as a helper function (but people might not notice/remember that it exists)
  - wrap the user's `f` in some code that performs this calculation and makes it available to the user as a metadata, an attribute, additional argument, etc.  To match #165, probably just a third argument to their `f` function.
- If there are problems due to gaps&edges in the previous approach, they might be resolved by creating a second df of time values with no gaps and extended around the edges, use hop2/slide2 instead of hop/slide; access to the second, df might make resolve some of the problematic cases for computing the `ref_time_value`. [On second look, this may not help; it looks like `slide_index2` doesn't take two index vectors.]
- We could move away from the slider package and just use a map.
- We could try to improve the slider package.
- We could try to implement an alternative slider-like routine.  (This might also benefit epi_archive [performance](https://github.com/cmu-delphi/epiprocess/issues/76).)

**Comment by brookslogan** [comment]
[Another approach](https://delphi-org.slack.com/archives/C028AUR6MV1/p1659236179493529) to correctly/simply recovering the `ref_time_value` by augmenting the original df / df group.

**Comment by nmdefries** [comment]
Link to the slider docs above is missing; an archived version is [available here](https://web.archive.org/web/20221005122536/https://davisvaughan.github.io/slider/reference/slide_index.html).

**Comment by nmdefries** [comment]
Closed by https://github.com/cmu-delphi/epiprocess/pull/318
