### ISSUE TITLE
Consider changes to help avoid bad automatic merges and diffs, accidental aliasing

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#175]
We encountered merge conflicts in tests where:
- git gives nonsensical automatic merge + diff that combines things from different tests which dealt with objects with the same names
- resolving a (sensical) merge conflict seemed potentially error-prone in the presence of object name re-use or a lot of objects defined outside of tests

Additionally, merge conflicts can appear due to whitespace and style changes.  Maybe we should implement some type of hook or check that makes sure we follow some standard indentation and trailing whitespace rules.

**Comment by dshemetov** [comment]
Closing as outdated.
