### ISSUE TITLE
Periodically bump version, perform GitHub release, maintain news/changelog

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#177]
Raised by @dshemetov a while back: we should periodically bump the package version and perform a GitHub release.  Maintaining a news/changelog file would also be helpful.  Version numbers help with lifecycle deprecation messaging.  We should think about how backwards-compatible we want to be, and how much we want to catch with deprecation messages.

**Comment by dshemetov** [comment]
I suggest a simple and common approach to version numbering (h/t @krivard): `A.B.C`, where `A` increments for large backwards-incompatible versions, `B` increments for large feature additions (backwards compatible), `C` increments for minor changes/fixes.

**Comment by krivard** [comment]
Credit: https://semver.org/

**Comment by brookslogan** [comment]
We're "at" version 1.0.0 for a while already but are still cleaning up some interface issues.  With current pull-into-main + semver we will reach ridiculous version numbers quickly.  It feels like we are more in < 1.0.0 by semver standards, so I'm thinking of doing something a little semver-incompatible until we stabilize more --- maybe just call the current version 0.x.y.z or 1.x.y.z with x.y.z semver-like (I think this might be sort of like 1.0.0-alpha-x.y.z, but in an R numeric_version-compatible way).  When we switch to semver proper we should consider moving to pull-into-dev, at least for breaking changes.

**Comment by dshemetov** [comment]
What do you think about [this viewpoint](https://tom.preston-werner.com/2022/05/23/major-version-numbers-are-not-sacred.html)?

**Comment by dshemetov** [comment]
I'm really just in favor of simple solutions. The reason I prefer sticking with the original SemVer is because adding epochal version numbers is 
- treading new ground in terms of the convention
- makes us non-compliant with their spec
- makes it more likely that we have further issues
- sets us up for having to make rules for what decides an epoch

I feel like you haven't really addressed my suggestion of just bumping the version numbers up and letting them get large. The benefits are:
- we stay in SemVer and avoid the issues above
- you can start doing it now, without issue, on the PRs you have now

We COULD also delete the 1.0.0 release, since that was just a test and I don't think any one is using it. And revert back to 0.z.w to get us back to alpha. Maybe that's what you're suggesting in your route 3. I think that would also be fine.

**Comment by dshemetov** [comment]
Also, it seems to me that the [test release of `epipredict` is actually 0.0.1](https://github.com/cmu-delphi/epipredict/releases/tag/v0.0.1), so I'm confused what the 1.0.0 discussion is about?

**Comment by dshemetov** [comment]
Rereading your comments about eventually getting back to SemVer, I think that's a good eventual goal.

So maybe if you want to have something like: `0.x.y.z` as a way to mark alpha for now and then when you have a first stable public release do `1.x.y`, that sounds fine to me.

**Comment by brookslogan** [comment]
Clarifications/notes:
- 1.0.0 discussion is about epiprocess.
- Current "meaning" of 1.0.0, was, as I understood it, that core functionality more or less worked, not that it was stable.
- Moving to semver >=1 mentality also influences development being on main vs. on a dev branch.
- epipredict discussion is about what to do in epipredict when certain pending breaking changes are made in epiprocess or if epiprocess changes to development on a dev branch.

Why not just have huge version numbers?
- It undermines any impression of commitment to trying to maintain backwards compatibility that we try to make in the future, because the user already sees we made 20 versions and may not be aware of any shift in mentality.
- We have been developing like we are at version `0.*.*`, or 1.0.0-alpha, not 1.0.0.  In a month we'll be somewhere like 1.0.0-beta.

Why consider epochs at this point?
- We still plan to go through a beta-like phase; maybe multiple / a beta-like and an rc-like phase.  An epoch might be one R-version-number-compatible way to indicate in the version tag itself when the/each beta phase is over; if we present back at some group, we can say this is something like version 4.*.* rather than 26.*.* (maybe harder to remember) or "Daring Dragon" (can't include in version tag) or 1.0.0-rc (can't do with R version numbers) or 1.0.0-26 (R can sort of do this, but may render it as (1.0.0.26, which is not, as far as I can tell, strictly semver-compatible, although maybe it's closer than epochs unless semver spec changes to add epochs).

If we decide to move to use epochs, it should be done fairly early on, so we don't start with a epoch number that's too high to look like an epoch number.  If we decide to move away from epochs, this can probably be done at any time without too much strangeness.

> Ok, final thought: a time-saving approach would be to just stay in `0.x.y` for now, not update `0` when the interface changes (because likely the interface changes in every update this early in the package). Just update `x` regularly to have distinct versions you can refer to and then when we finally decide we're at `1.0.0`, release that, have it be marketing-meaningful, and THEN start tracking interface changes.

Sounds solid; previously, I was reluctant to do this since we already had 1.0.0 in the DESCRIPTION on `main`.  But let's just call labeling in the DESCRIPTION file not a release.  I'm not sure whether or not this will cause issues for people developing on epipredict who need to update epiprocess for testing; perhaps that can be saved by developing off of a 1.0.0 `dev` branch or some manual reinstall.  (I suppose if we want more flexibility, then, instead of epochs, we could do use dev branch development or pre-releases instead (and live with any hyphen-to-dot conversion, and hope that a new semver doesn't introduce epochs and distinguish between epoch vs. numeric pre-release by looking at dots vs. hyphens).)

**Comment by dshemetov** [comment]
Thanks for the clarifications Logan. 

Agree that DESCRIPTION file labeling isn't enough to constitute a release (it's not attached to hosting, for one). Personally vote for `0.x.y` for now, just to stay compatible with SemVer, and adopting their [initial development spec](https://semver.org/#spec-item-4). 

Also vote in favor of developing on a `dev` branch. That way main can always point to the latest stable release and dev can have the latest unstable work.

**Comment by dshemetov** [comment]
Made releases for the past few versions. Next steps:

- [ ] rename current `main` to `dev` (so PRs automatically follow the right branch)
- [ ] make `dev` the default PR 
- [ ] make a new `main` (we will merge here when we're ready to make a release)
- [ ] recommend installations pin their epiprocess versions to a GitHub release
- [ ] update generic installation instructions to `pak::pkg_install("cmu-delphi/epiprocess@main")`

**Comment by dshemetov** [comment]
closed by #398 and related changes
