### ISSUE TITLE
Revisit #67: are we happy with current reference semantics scheme

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#181]
We completed the alternative approach to #67:
- R6 methods are potentially-mutating, potentially-aliasing.  If they mutate, they should generally return `invisible(self)`.
- S3 wrappers are non-mutating, potentially-aliasing.

The specifics of guaranteed/potential/never mutation, aliasing, and reseating should be described in each function/method.

However, there are some annoyances and gotchas here:
- Having to implement + carefully document method + wrappers.  (Higher implementation effort + user doc-reading effort)
- `clone` not `copy`ing the DT
- worrying about aliasing
- other reasoning/gotchas about reference semantics

For what seems to be little benefit, as:
- I don't think any of the methods actually mutate the DT, but rather reseat it.  (And even if they did mutate, they might have been able to do it just via dtplyr.)
- We implemented our own custom `print` for R6 class(es), negating the usefulness of the auto-print implementation
- We have `epix_` wrappers in the namespace, negating the anti-namespace-pollution of R6
- Potentially allowing us to have a more natural mutating interface for archives that can update/sync themselves, although we haven't done the interface sketches to establish this.

We should revisit #67 after playing around with / getting potential-user feedback on the current approach.

**Comment by ryantibs** [comment]
Just checking because I may have lost track: What happened to the behavior of `merge()`? Did we implement the suggestions in #67?

**Comment by brookslogan** [comment]
Yes, the "alternative approach":
- `epix_merge` does not mutate `x` or `y`
- `x$merge` stores the result in `x` and returns invisibly

and I believe that all `epi_archive`-related methods we provide now follow the rules that:
- `epix_<method>` does not mutate input `epi_archive`s, but may alias them or alias their fields
- `x$<method>` may or may not mutate `x`; if it mutates, it will return `x` invisibly (where this makes sense), and may or may not reseat its fields (and, at least for current operations, if it does reseat a field, won't mutate the object the field used to refer to); if it does not mutate, its result may contain aliases to `x` or its fields.

(In the particular case of merging:
- `epix_merge` does not mutate `x` or `y`, and does not contain aliases of either of their DTs
- `x$merge` mutates `x` by reseating its `DT` and some other fields, but avoids mutating the old `x$DT`, and returns `x` invisibly)

This scheme is consistent in the essential stuff regarding mutation, and should be user-friendly for non-R6 users that stick to the `epix_*` functions and don't reseat the fields or mutate the `DT`.  The main reason why I filed this issue to revisit is on the development side: the dual interface, extra reasoning and documentation, and `data.table` special cases make things a bit harder to work on.  If we feel it slows things down enough and doesn't provide user benefits, then we may think about some alternative approaches (dtplyr? custom data structure? check on the status and speed of dplyr non-equi-joins?).

**Comment by ryantibs** [comment]
Excellent thank you

So just to check I fully understand the behavior of `x$merge()`, if I had an `epi_archive` object `x`, and I did this: 
```
DT = x$DT   # Pointer to the original DT
x$merge(y)  # Merge with epi_archive y
```
Then after the last line, `x$DT` should be updated, but `DT` should not?

**Comment by brookslogan** [comment]
Right.  (Additionally, modifying `x$DT` afterward should not modify `DT`. --- Thinking about this now, I'm not sure it was good to document this as a given though, as it might be incompatible with a lazy merge implementation.  The docs might need to change to "may or may not contain aliases to the DTs of x and y".)  This is a specific behavior of `$merge` and not a general thing about the R6 methods as written; others might accomplish their operations by mutating the contents of `x$DT` (changing `DT`) rather than reseating `x$DT` with a new data table containing the result.

**Comment by brookslogan** [comment]
From further discussions and experience, I think the answer is "no".  --> #340
