### ISSUE TITLE
"Promote" `other_keys` to be printed, a constructor parameter, and more clearly documented

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#186]
Migrated from #113 and #183.
- `print.epi_df` should print the `other_keys` metadata.
- `other_keys` should be its own parameter to `new_epi_df` and `as_epi_df`
- Unfortunately, I don't think we ever explained what "keys" were in the context of an `epi_df`, and googling "tibble key" is surprisingly unhelpful (currently giving links to lock picks and decoder tools) [so the `{new,as}_epi_df` docs may need explication].  Maybe explaining this could just be rolled into the issue for adding `other_keys` as a parameter, though; it'd be easier to do in its own `@param`.

If this is causing recurring issues in epipredict maybe it should be changed to higher priority.

**Comment by brookslogan** [comment]
We should probably also make `other_keys=character(0)` the default.

**Comment by brookslogan** [comment]
And we should also print the rest of the epikey in `epi_archive`'s print method as well (e.g., after the geo and time type).

**Comment by brookslogan** [comment]
We need to regenerate the saved data sets after this change, or maybe right now due to the `other_keys` default change, or add notes in implementation to try to maintain backwards compatibility with saved edf's, or...

**Comment by dsweber2** [comment]
When "you say after this change", are you referring to the default of `other_keys` switching to `character(0)`?
