### ISSUE TITLE
Add code coverage tools somewhere and/or a dev guide

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#204]
E.g., something to help catch the missed test case that caused the bug in https://github.com/cmu-delphi/epiprocess/issues/200.

We will need to think about whether this should be in CI,  part of some sort of development guide.  (Other things to put in dev guide: coding&testing standards, suggested editor configs.)

**Comment by dshemetov** [comment]
Closing this as outdated.
