### ISSUE TITLE
Improve checking for out of bound `ref_time_values` when using `epi_slide`.

### ISSUE THREAD

**Issue by kenmawer** [cmu-delphi/epiprocess#206]
Currently, an error is thrown only if ALL `ref_time_values` are out of bounds. If this value is contained, but other values within bounds are contained, the out of bound value is omitted, with the values within bounds being used for the `epi_slide`.

**Comment by dshemetov** [comment]
Closing as outdated. This behavior is as intended.

**Comment by brookslogan** [comment]
(The behavior described here wasn't intended, but it's already been replaced with more sane behavior: requiring that all `ref_time_values` appear as `time_values` to proceed, rather than requiring all to be out of bounds to be an error.)
