### ISSUE TITLE
Change `n` -> `before`, `after` in `detect_outlr_rm`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#214]
Split out from [discussion](https://github.com/cmu-delphi/epiprocess/pull/188#discussion_r947114531) on https://github.com/cmu-delphi/epiprocess/pull/188.

**Comment by kenmawer** [comment]
Just so you know, `rm` confused me at first, as I thought it meant "remove" rather than "rolling median."

**Comment by brookslogan** [comment]
We've moved back to `.n` + `.align` in `epi_slide*`, so this doesn't make sense (unless maybe we wanted to add a `.align` arg here).  Refiling naming comment in another issue.
