### ISSUE TITLE
Fix particular outstanding doc and vignette issues

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#217]
- [x] Fix `"%s"` in `epix_fill_through_version` docs.
- [x] "[...] typo in the readme file("functions in the epiprocess package that operate on epi_df objects begin with epix", should be "epi_archive" objects)" --- thanks to Tianyue for flagging
- [x] Fix `as_list_col` confusing doc: "Should the new column be stored as a list column?" --- Roughly, "new column" should be "computations"; maybe edit some other words.
- [x] Remove `compactify`-is-not-metadata discussion from vignette.

Copy-pasting some additional items identified by Ryan in an old Slack thread:
- [x] on [this page](https://cmu-delphi.github.io/epiprocess/), we advertise “Get the epipredict R package” but the link takes you back to epiprocess
- [x] same page, we should probably advertise “Get the [epidatr] R package”, and not covidcast, when the former is ready
- [x] on [this vignette](https://cmu-delphi.github.io/epiprocess/articles/correlation.html), now that somebody changed the date range (?) from when I initially wrote it, some things look funny. The blue density for the lag 10 correlation (about halfway down) is weirdly bimodal. Also the argmax lag is now 22 (last plot) and not 18, as the text claims
- [x] In the reference index, we should write the titles using code style, so epi_df instead of epi_df, etc., because this is now possible: https://github.com/r-lib/pkgdown/pull/2113
  - [before/after: check that GitHub Actions pkgdown has this update or otherwise does something reasonable]
- [x] We should go through and make sure that no messages/warnings appear in vignettes that are not important. Like any package loading message or warning, and silly ggplot message or warning , etc. I thought I caught all of them when I wrote vignettes but I either missed some or some new ones got introduced.
- [x] The "Attribution" section at the bottom of each vignette page starts with "This document contains dataset ...". Let's change that to "This document contains a data set ..."

**Comment by ryantibs** [comment]
Thanks @brookslogan for organizing these! I think this should be pretty quick work, can we make this happen sometime soon? (Or you can figure out somebody new-ish to delegate this to? Thank you.)

One more thing to add. The "Attribution" section at the bottom of each vignette page starts with "This document contains **dataset** ...". Let's change that to "This document contains **a data set** ..."

**Comment by brookslogan** [comment]
Regarding the correlation vignette plotting change:
- This change looks like it was from a change in the `geo_values` stemming from:
  - a move to use internal data in vignettes rather than query the API each time, in order to make vignette building faster and more reliable (504f2fe65c6d110e4453a7588a2e5ffc8671a78e), plus
  - a decision to make the sample data objects small to avoid bloating the repo and package with large data sets (and maybe also improve vignette build time?).
- On my machine, the build time difference is 2s vs. 11s.  For context, other vignettes take around ~10s as well, and `growth_rate.Rmd` and `compactify.Rmd` are major time hogs, taking ~1min a piece.  `build_vignettes()` takes around 3min. 10s longer for vignette building and maybe 20s longer for checks isn't going to break anything; I'm basically just going to revert back to querying the API for all `geo_values`.
- Later TODO: consider making an `epiprocess.data` package containing larger sample data objects, including the data for this vignette.
- Later TODO: try to make vignette building work at interactive speeds.

**Comment by dshemetov** [comment]
- [ ] [Tianyue's documentation review](https://docs.google.com/document/d/1MgPWCduuukJUa3sjEvMsj3xv1-kW8fR3azcA717Tq9I/edit).

**Comment by nmdefries** [comment]
Moved remaining issue about vignette build speed to https://github.com/cmu-delphi/epiprocess/issues/363
