### ISSUE TITLE
Debug sluggish archive tests, assess usability/scalability of recent archive features

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#218]
Archive tests on really minimal archives are taking over half a second to run.  Profile to debug / more importantly, see if archive performance is acceptable for non-toy archives.  A small step toward this: using profvis on a 100-times-repeated version of the body of the "epix_fill_through_version does not mutate x" test suggests that a whole lot of time is being spent in the tidyselection for the filter for the compactification check.  For testing toy archives, this is a minor annoyance (longer pkg test times); for non-toy archives in real use, we expect that overhead not to matter.  However, we want to double-check the compactify performance vignette and profile recently added/changed archive operations for performance on non-toy examples.

**Comment by brookslogan** [comment]
Downgrading; initial test suggests this is just a nonideal amount of fixed overhead.  We should think about some sort of automatic benchmarking at some point, though, not just relying on initial experimentation before committing being sufficient.

**Comment by dshemetov** [comment]
Closing as outdated.
