### ISSUE TITLE
Add doc topics for alias&mutate&reseat; consider alternative to "mutate", hiding details of wrappers

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#224]
Related to, and may be obviated by alternative work arising from, #181.

Add roxygen topics for alias, mutate, and reseat, and link to them in other roxygen docs discussing them.  Maybe also some vignettes.

Consider an alternative term for "mutate" (as in side effects) so this term doesn't conflict with `mutate` (the non-mutating `dplyr` verb).

In the roxygen docs for the wrappers for R6 functions, the user is shown details about aliasing, mutation, and reseating, but the wrapper functions are built so that a user that only uses them (not using the R6 methods or directly mutating the archive or its contents) doesn't have to think about them (besides maybe some performance considerations).  Consider whether there is a sensible way to hide or "demote" these details and put all details and warnings only in the R6 functions.  (There may not be a way while the R6 methods and the DT are still available; R6-aware users will want to know if wrappers must, may, or must not alias (vs. clone) the archive, DT, or DT cols.)

**Comment by dshemetov** [comment]
Closing as outdated, since R6 was removed.
