### ISSUE TITLE
Consider adding dev editor config, setup guide, styler, styler hooks

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#226]
Consider
- adding some editor configuration files to help maintain a consistent style
- adding a development guide for the same purpose + discuss branch&PR setup, running `check()`, etc.
- running through `styler` and adding `styler` hooks

For editor config, maybe the following for Emacs ESS:

`.dir-locals.el`
```el
((ess-r-mode
  . ((ess-style . RStudio) ; seems to match or is close to existing style
     )))
```
and guidance to consider adding
`.dir-locals-2.el`
```el
((ess-r-mode
  . ((comment-add . 0) ; to get commenting commands to avoid "##" in order to
                       ; match this style until
                       ; https://github.com/emacs-ess/ESS/issues/996 is
                       ; resolved, but triggering a may-not-be-safe message
     )))
```
and to instruct Emacs that this is safe when it asks (--- have this in guidance to avoid scary "safety" messages for regular users browsing code).

**Comment by dshemetov** [comment]
Styler was added in #425. Development guide was added a while ago. Adding editor config in #538 .
