### ISSUE TITLE
Remove issue queries for 7dav data

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#230]
Eventually queries for 7dav issue (but not as_of) data will be going away, and we'll want to use slides / caching derived archives to calculate them anyway.  We should change all (archive) data objects, examples, vignettes, etc. to avoid these queries.  Also check `epipredict`.

**Comment by brookslogan** [comment]
JIT isn't happening soon; we want this instead to give correct results on some signals with bad 7dav data, or just for the functionality.

**Comment by brookslogan** [comment]
We probably don't need this for any of the current vignettes.

**Comment by dshemetov** [comment]
Closing as outdated.

**Comment by brookslogan** [comment]
This is still sort of relevant due to potentially-buggy vignette data https://github.com/cmu-delphi/epidatasets/issues/9, but I think we have the required archive -> archive transforms probably in some other issues.
