### ISSUE TITLE
Allow multiple column computations in data masking slides

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#235]
Currently, only a single data masking expression can be fed into `epi[x]_slide`; e.g., trying to compute 7davs of two signals simultaneously requires using a function/formula `f` or `as_list_col=FALSE`.  (Plus, the evaluation environment(s) for the data masking expression might not quite be correct, and `as_list_col=FALSE` on a single data masking input doesn't match dplyr patterns, plus adds a name prefix that is very likely unwanted for the tidyeval case and maybe in general.)  Allow multiple data masking expressions to be provided, and make sure to pass appropriate environments.  Maybe give some extra thought to make sure `dplyr::cur_*` functions work properly, although note [these caveats](https://github.com/cmu-delphi/epiprocess/issues/55#issuecomment-1287185892).

**Comment by brookslogan** [comment]
- [ ] Check, e.g., `advanced.Rmd` to remove potential references to `epix_slide` outputting one row "for element/row output from calls to `f`".

**Comment by dshemetov** [comment]
This is done as of #477 and possibly earlier @brookslogan ?

**Comment by brookslogan** [comment]
#477 sounds right for the multiple column computations; row requirements were relaxed earlier and it looks like the docs were updated already.
