### ISSUE TITLE
Improve vignette variable naming, patterns, dependencies on data-raw

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#248]
Debugging vignette errors is a made more difficult by:
- non-explanatory variable naming
- `eval=FALSE` chunks that have fallen out of sync with the actual data being extracted from objects in data-raw
- bindings being overwritten, so repeating error behavior sometimes repeating the initial binding + some rebindings while avoiding `eval=FALSE` chunks

Improve vignette variable naming while reducing the amount of binding&object mutation that occurs.  Add a development guide and/or notes in data-raw that instruct developers to update vignettes accordingly whenever updating data-raw scripts.

Also consider turning `echo=FALSE` chunks loading data objects into visible chunks with an explanation for the reader.  (So they can run things more quickly.)

**Comment by brookslogan** [comment]
Or, for the nonevaluated API + nonechoed data object chunk pairs, consider just eval+echo the chunk using the example data.

**Comment by dshemetov** [comment]
Going to close this in favor of #363
