### ISSUE TITLE
Add a `complete` method for `epi_df`s

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#250]
Currently, we expect users to appropriately `tidyr::complete` their data appropriately before using with some `epiprocess` functionality, but `complete` on `epi_df`s drops `epi_df`-ness; we should stop that from happening.  (If we were to enforce key uniqueness, this might need to be done carefully or with some additional checks, but since we don't, it's probably just unconditionally `reclass`ing or `dplyr_reconstruct`ing).

**Comment by brookslogan** [comment]
Adding a `complete` method may not be the "right" approach.  It might naturally fall out of fixing more core functionality like joins.  Related: #223.

**Comment by brookslogan** [comment]
Migrating from #138.

> This might be a tool to use in #256; if we want to complete slide inputs, we may need a complete / gap-filling method for that works across both `epi_df`s and tibbles (depending on whether our slide inputs have been decayed into tibbles or are still `epi_df`s). `tidyr::complete` may or may not work for this already, but it's probably what we want to use. We're trying to avoid heavy tidyverts dependencies now.

**Comment by dshemetov** [comment]
Added in #488
