### ISSUE TITLE
Consider allowing `f` in `epi[x]_slide` to be an unnamed data masking expression yielding a tibble

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#255]
This would improve compatibility with `dplyr`.  However, it may introduce some ambiguities with the function&formula `f` case, and require some modifications to exactly how these cases are evaluated: if there is an `f` but no `...`, we can't immediately distinguish between functions, formulas and data masking expressions; e.g., just using `class` won't work as it would force data masking expressions.  Instead, we would need to (defuse and) evaluate `f` itself using data masking, then check the result's class: functions and formulas would need to be (validated and) evaluated in the normal fashion, while tibbles would be unpacked into multiple columns as in `mutate` and `summarize`.  For consistency, `f` may also need to be evaluated in this way even if args are provided in `...`, but we should only allow args in `...` if it's actually a function (or formula?).

Generalizing `f` in this way may make it harder to validate `f`, and may make it impossible to immediately validate `f` without access to any data.  Thus, whether or not to proceed may require some thought.

**Comment by dshemetov** [comment]
This is addressed in #477 right? @brookslogan

**Comment by brookslogan** [comment]
Yes.  We side-stepped the tricky implementation here by just requiring the user add an extra comma... perhaps not ideal, but these seem like power-user features anyway and they can deal with it.
