### ISSUE TITLE
Consider replacing `as_list_col`, `names_sep` with `dplyr` behavior

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#261]
We might want to make things more dplyr-like by not prefixing to begin with, eliminating `as_list_col` and let users just wrap their output in a list if they want the corresponding output column to be a list, and eliminating `names_sep`.  (Might avoid confusion leading to filing #229.)  Relates to #240.

Not sure if we should treat this as a P1 instead, as this would be a breaking change for users that do rely on the prefixed-unnest behavior.

**Comment by brookslogan** [comment]
Another point of confusion this could avoid: if we provide a computation outputting atomic vectors, slides with `as_list_col=TRUE` won't actually output a list col.

**Comment by dshemetov** [comment]
These were removed in #477
