### ISSUE TITLE
Consider allowing negative `after` values

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#287]
In `advanced.Rmd`, we fit a nowcasting model for y given x using `epi_slide`.  However, beyond the latency&revision-naiveness, it is also will give unrealistic performance because it includes the testing data in the training data.  If we want to enable this type of operation (questionable; should we route solely to `epi_archive`?), it'd be nice to be able to set `after = -k` when the reporting latency is expected to be `k`.

**Comment by brookslogan** [comment]
See discussion in #288 for why we `after = -1` would not be appropriate here unless we separated the fit (slide with before = 2, ahead - 1) and predict (mutate/etc.) steps.

Perhaps a more important use case, motivating the addition of an `after` parameter and allowing it to be negative would be for `epix_slide` extracting a particular lag (though doing this for each lag doesn't sound great for efficiency; maybe this needs to be its own function even though technically we could do it with an `epix_slide`).

**Comment by dshemetov** [comment]
Closing as out of date. We no longer have the `after` argument.
