### ISSUE TITLE
First pass at making "Getting Started" guide better

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#350]
Currently, "Getting Started" has installation instructions + a bunch of stuff on getting things into epi_df format + some plotting + nothing on other features of the package.

Suggestion:
- Migrate the epi_df stuff to another vignette or combine it with another vignette.
- Have Getting Started be installation instructions + pointers to various function reference pages and/or vignettes / the tooling book.

Or is there a way to just eliminate the Getting Started guide and just have the landing page serve that purpose?

**Comment by nmdefries** [comment]
Landing page = installation + very basic usage 

Getting started = medium-complexity use? Description of what you might want to do with links to relevant vignettes?

**Comment by dshemetov** [comment]
- Attributions on the Getting Started page are a little awkward
- No epi_archive examples
- No discussion of the benefits of using an epi_df

**Comment by dsweber2** [comment]
> Can we demo "easier" data sets than Covid cases (where forecasting is more tractable) or provide better context about performance

From a bullet point on an OKR, probably a good way to make this concrete
