### ISSUE TITLE
Fix typo in reference to metadata attribute

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#36]
There appears to be a typo accessing the metadata attribute [here](https://github.com/cmu-delphi/epiprocess/blob/65285dff99db96e1c5b163118e6fd155f471d307/R/epi_df.R#L185); alternatives are:
```
attributes(x)$metadata
attr(x, "metadata")
```

**Comment by ryantibs** [comment]
I'm not sure when this was fixed but I did notice it at some point and it's fixed now. Sorry for not tracking this more rigorously!
