### ISSUE TITLE
"Slide" vignette reference to and conclusions about Texas reporting need to be expanded

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/epiprocess#367]
The ["slide a computation" vignette](https://cmu-delphi.github.io/epiprocess/articles/slide.html#slide-the-tidy-way) says “As we can see from the top right panel, it looks like Texas moved to weekly reporting of COVID-19 cases in summer of 2021.” 

> Texas is in the bottom right panel instead of the top right.

Some possible causes: the move from `covidcast` -> `epidatr` changed classes somehow, the API response's row ordering changed due to internals or to revisions, or there were updates to dplyr. We may want to check how this changed to make sure it doesn't shift underneath us again, or make the wording not mention plot location.

> And how can we draw this kind of conclusion? This needs more explanation. GA has roughly the same curve as TX, can we also conclude that GA moved to weekly reporting?

I think this is from looking at the bars behind the lines.  They aren't very visible right now; maybe we need to widen the plot and move to `ggplotly` to allow interactivity.  We should check whether this conclusion is actually true, in addition to explaining and addressing GA (and FL?).

**Comment by dshemetov** [comment]
Comment two is out of dated, there's no more commentary on GA. Fixing the TX comment in #538.
