### ISSUE TITLE
"archive objects and data revisions" vignette cleanup

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/epiprocess#373]
See https://cmu-delphi.github.io/epiprocess/articles/archive.html

- [ ] In the Producing snapshots in epi_df form part, max(x_snapshot$time_value) should be “2021-05-29” instead of “2021-05-31”.
- [ ] When run the code after updating the date above, `merge(x, y)` raises an error. It says x and y are not equally up to date version-wise. May have to add `sync = ‘na’` to make it work.

**Comment by dshemetov** [comment]
This appears to be out of date, as I can't find `max(x_snapshot$time_value)` in question.
