### ISSUE TITLE
Clean up error messages and assertions

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#380]
- [ ] Add helper functions to validate f_args
- [ ] Remove the `Abort` / `Warn` plugins
- [ ] Replace all warnings/errors with functions from `{cli}` and appropriate error messages.

**Comment by dshemetov** [comment]
@dajmcdon do we still need (1) if we're using `checkmate`?

**Comment by dajmcdon** [comment]
Possibly. Or, maybe 1 simply gets subsumed with 2.

**Comment by dshemetov** [comment]
Got it. I'm starting to notice a lot of hand-written arg validation functions like:

```r
validate_version_bound <- function(version_bound, x, na_ok,
                                   version_bound_arg = rlang::caller_arg(version_bound),
                                   x_arg = rlang::caller_arg(version_bound)) {
```

I'm thinking we can replace these with checkmate calls.
