### ISSUE TITLE
Fix archive `additional_metadata` docs + maybe rename (or remove?)

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#396]
Current docs include
```
#' @param additional_metadata List of additional metadata to attach to the
#'   `epi_archive` object. The metadata will have `geo_type` and `time_type`
#'   fields; named entries from the passed list or will be included as well.
```
The archive's `$additional_metadata` doesn't actually get geo & time type attached, but looks like if there are `other_keys` that they would be put there.  If it does have this extra stuff attached, it should be called `metadata` instead, similar to `epi_df`.  But do we even need an `$additional_metadata`?  Why not just an `$other_keys`?  If users want to attach more metadata, they can just use `attr<-`; we're not doing anything special/extra.

**Comment by dshemetov** [comment]
Closing as we don't have `additional_metadata` anymore and the docs have been removed.
