### ISSUE TITLE
deprecate internal arg_check funs in favour of `{checkmate}`?

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#403]
suggestion (optional): Looks like these type-check fns could be replaced by `checkmate::assert_double` or `checkmate::check_double` if you want to raise a custom error message, and analogues for other types.

_Originally posted by @nmdefries in https://github.com/cmu-delphi/epiprocess/pull/382#discussion_r1462207988_

**Comment by dshemetov** [comment]
I'm happy to take a stab at this, did a lot of this work in `epidatr`.

**Comment by dshemetov** [comment]
Done in #410
