### ISSUE TITLE
Write something intelligent at the bottom of growth rates vignette

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/epiprocess#41]
I just recently implemented a `growth_rate()` function, which now merges/replaces any of the functionality for estimating relative changes and derivatives and the like, in the `epiprocess` package. The new [growth rate vignette](https://cmu-delphi.github.io/epiprocess/articles/growth_rate.html) likewise replaces the old relative change and derivatives vignettes.

At the [bottom of that vignette](https://cmu-delphi.github.io/epiprocess/articles/growth_rate.html#log-scale-estimation), I demonstrate how all the functionality works on the log scale. Something interesting happens: the relative change estimates look like they become less volatile and match the linear regression estimates much more closely. 

I want to write something intelligent here but I ran out of energy and intelligence. @jacobbien @dajmcdon You guys are intelligent guys, did you want to take a ponder and give it a shot?  

Also I would like to leave some intelligent general comment about when we might do things on the log scale versus not, based on our working assumptions about the noise model.

**Comment by jacobbien** [comment]
Here's my interpretation for the first part of this issue:

> Something interesting happens: the relative change estimates look like they become less volatile and match the linear regression estimates much more closely.

Let's write `R = (A - B) / B` for the relative change (A = "after"; B = "before").

The question is why first differences on the log scale look less volatile.  To relate these two approaches, note that

`log(B) - log(A) = log(B/A) = log(1 + R)`.

We are doing averaging over a window, so the observation is that

`E[log(1+R)]` looks less volatile than `E[R]`.

There are two relevant inequalities for relating these, both based on the concavity of log:

`E[log(1+R)] <= log(1+E[R]) <= E[R]`.

The first inequality is Jensen's; the second inequality is because the tangent line of a concave function lies above it.

Here is the plot for GA, where 

`Red = E[log(1+R)]`,
`Green = log(1+E[R])`, and
`Blue = E[R]`.

![Screen Shot 2022-02-14 at 9 24 29 AM](https://user-images.githubusercontent.com/2008608/153914667-18ae678f-53da-416a-bfde-67dfec7c97a5.png)

It shows that both inequalities are relevant here, but that Jensen's accounts for more of the difference.

**Comment by jacobbien** [comment]
I modified the code from the vignette to make the above plot.  Here's the code if you'd like to reproduce:

```
library(covidcast)
library(epiprocess)
library(dplyr)
library(tidyr)

x <- covidcast_signal("jhu-csse", 
                      "confirmed_7dav_incidence_num",
                      start_day = "2020-06-01", 
                      end_day = "2021-12-31",
                      geo_type = "state", 
                      geo_values = "ga")  %>%
  select(geo_value, time_value, cases = value) %>% 
  arrange(geo_value, time_value) %>%
  as_epi_df() 

x_h7 <- x %>% 
  mutate(
    time_value,
    gr_rc = growth_rate(time_value, cases, method = "rel_change",
                        log_scale = FALSE, h = 7),
    gr_log = growth_rate(time_value, cases, method = "rel_change", 
                         log_scale = TRUE, h = 7),
    gr_log2 = log(1 + gr_rc))
x_h7 %>% 
  select(-geo_value, -cases) %>% 
  pivot_longer(-time_value) %>% 
  ggplot(aes(x = time_value, y = value, color = name)) + 
  geom_line()
```

**Comment by dajmcdon** [comment]
Adding to Jacob's characterization: I think `E[log(1+R)]=H(A)-H(B)`. Here `H(A)` is the entropy of `A` , and the same for `B`. So the left hand side of the Jacob's Jensen string likely has some type of interpretation as a measurement of uncertainty, though my information theory is not strong enough to say what this interpretation might be.

**Comment by ryantibs** [comment]
@jacobbien Thanks! This is great. The math generally makes sense, but I'm confused about one thing (last bullet point): 
- I think you mean R = (B-A) / A (this is already the notation I use in the vignette too, except I'm just adjusting for a non-unity bandiwdth, h)
- I don't really understand what you mean when you saying you're showing an expectation in the plots? To me, red = log(1+R), blue = R. 
- In that light, I don't know why green doesn't match blue. Is this just numerical error? It looks too large to be numerical error. What am I missing?

Ohhh I think it must be the bandwidth h being non-unity. In general the two quantities in question should be:
1. ((B - A) / h) / A = (B/A - 1) / h 
2. (log(B) - log(A)) / h 
If we call R the first one, then the second one is log(h(1+R)) / h.

**Comment by jacobbien** [comment]
@ryantibs Yes, exactly, the bandwidth being non-unity is why blue and green are different.  When I write the expectation above I meant that to represent the averaging that you do in the code over h consecutive time points (when you are computing what you call `a` and `b` in the code).  Obviously it could represent more general averaging (wrt some noise model), but for explaining the exact observation here, averaging over h is what is relevant.

Notation:
- Sorry for swapping `A` and `B` relative to the vignette's definition.
- If you define `R = ((B-A)/h) / A`, then I think it should actually be compared to `(log(B) - log(A)) / h = log(1 + h * R) / h` (i.e., the h should not multiply the 1 in the log). Right?

**Comment by ryantibs** [comment]
Thanks! All makes sense including your last catch about me having h in the wrong place (was just moving too quickly with mental math)! 

Can you please make a PR to extend the vignette at the end to explain some of this in a way that's informative but also pretty short (e.g., I don't think we need to make any more plots, just give your explanation in terms of Jensen's etc.)?  

Or if you want to wait until we've thought about the "noise model" remark, we can do it all in one go---up to you.

**Comment by ryantibs** [comment]
I'm going to go ahead and close this. There's a todo hidden in a comment in the growth rate vignette to remind us about the relationship between log and the working noise model.  But @jacobbien addition was interesting enough (thanks again) that I think it's worth moving on.
