### ISSUE TITLE
Delete incorrect comment regarding `as_tibble`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#417]
We say that `as_tibble` de-aliases `data.table` columns [here](https://github.com/cmu-delphi/epiprocess/blob/fd2339d8379455fda1ff27cc078fb23be5c3a93c/R/archive.R#L516), but it doesn't.  We should still probably be good since `[.data.table` with an `i` arg (but not `unique.data.table`, probably a bug) seems to consistently copy.  It's just the comment that's wrong.

**Comment by brookslogan** [comment]
If we wanted to be more careful here, we could try to detect aliasing & copy in that case, like we do post-`unique` in another portion of the code.

**Comment by brookslogan** [comment]
Another probably-inaccurate comment:
```
  # We don't want to directly use `dplyr::mutate` on the `$DT`, as:
  # - this likely copies the entire table
```

**Comment by brookslogan** [comment]
It might actually be okay to alias in these cases if we never mutate archive DT columns without copying first.  I'm not sure whether that's the case or not though.  It seems plausible, since IIRC we don't really do partial column modifications, though there are still key-ing operations that might be of concern.

**Comment by dshemetov** [comment]
This is out of date, these comments were removed/modified a while ago.
