### ISSUE TITLE
Implement testing across the package

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/epiprocess#42]
Now that the package is getting farther along, I think it is about time we implement testing across the package. Especially because I believe (and hope) that more others will be contributing to it in the near future.

@capnrefsmmat You are our resident stickler-for-the-rules-kind-of-guy, did you want to take the lead on this? You know I'm kidding 😛, and I would be grateful if you took this on.  I think @qpmnguyen @rafaelcatoia could be willing to help as well, so if you have some ideas/scaffolding then perhaps they would be willing to implement it with you.

**Comment by qpmnguyen** [comment]
Hello! Happy to help write unit tests!

**Comment by ryantibs** [comment]
@qpmnguyen @rafaelcatoia Did you guys want to start taking a look at this? You can see the way that testing is implemented in the covidcast R package (for example) and also read up on testing in R in general if you haven't had exposure to this already.

In side conversation with @capnrefsmmat, he said he is busy for a little bit with other responsibilities, but can start taking a look perhaps mid March, so in any case I think it makes sense for Quant & Rafael to just start learning/putting things together in the meantime, if you're still up for it.  Thanks!

p.s. in the `advanced.Rmd` vignette, I have some code chunks with `include = FALSE` that were basically just some hand-tests I was running to make sure the results were what I expected with sliding. In building tests, you could remove these chunks from that vignette (they're not needed there anymore, they're just in there so I didn't forget them) and incorporate them into the tests you're writing.

**Comment by dajmcdon** [comment]
@dshemetov @qpmnguyen @rafaelcatoia Is anyone actively working on this? I'm going to re-assign if no.

**Comment by dshemetov** [comment]
I'm not.

**Comment by kenmawer** [comment]
I submitted a pull request for a test, `correlation`.

**Comment by kenmawer** [comment]
I just realized that the following do not have tests:
`archive.R`
`growth_rate.R`
`methods-epi_archive.R`
`slide.R` (may not be necessary as `epi_slide.R` is already tested)

**Comment by brookslogan** [comment]
Tests for the above have now been addressed in PRs (e.g., #159, #197); closing as completed.  We may want to push on #204 to catch anything else hiding untested.
