### ISSUE TITLE
[enh] promote `other_keys` 

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#446]
Can we move `other_keys` out of the `additional_metadata` List? This seems like, by far, the most common use case we've seen for this list. And it already has its own special handling in the `new_epi_df()` constructor.

**Comment by brookslogan** [comment]
Yeah, we definitely need to get to this, and just remove the other `additional_metadata`.  We don't handle that any better than direct `attr`s.

Probably a dupe of #186

**Comment by brookslogan** [comment]
I [think](https://github.com/cmu-delphi/epiprocess/pull/460#issuecomment-2187664111) this was magicidentally closed.
