### ISSUE TITLE
`epix_slide` allows `time_value` and `version` to be different types & do unintended things

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#448]
E.g., `tsibble::yearweek` and integer (yearweeks are probably treated like number of weeks since some epoch; assuming this is the case since `tsibble::yearweek(int)` appears to work this way rather than e.g. parsing approach of epidatr).  We do want to allow mixed types at some point; e.g., time_values representing weeks and versions representing datetimes.  Datetime versions are likely more complicated, as, e.g., they probably won't have a regular period.

**Comment by brookslogan** [comment]
@dshemetov seems relevant to what you're working on, not sure if you'll automatically knock this one out with changes you have planned.

**Comment by dshemetov** [comment]
Thanks yea, haven't looked deeply, but looks relevant and hopefully something I can address.

**Comment by dshemetov** [comment]
closed by #472
