### ISSUE TITLE
`as_epi_df` construction conviences

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epiprocess#456]
A couple of things I realized would be convenient when trying to use `as_epi_df`:
- allow for common `time_value` aliases. E.g. if `date` or anything containing that is present and unique, just assume that the user means that that column should be used as the `time_value`. Maybe `info` that it's happening.
- if no `geo_value` is present, assume that all values have the same geo_value at a national scale
- give an `alias` argument that allows the user to input e.g. `geo_value = some_col, time_value = date`. This is basically just allowing them to skip writing a `rename` immediately before `as_epi_df`

**Comment by dsweber2** [comment]
@lcbrooks @nmdefries would like your opinion at some point on whether we ought to do this

**Comment by dshemetov** [comment]
closed by #460
