### ISSUE TITLE
Resolve "... may be used in an incorrect context" check warnings

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#465]
~This appears to be [causing checks to be marked as failures](https://github.com/cmu-delphi/epiprocess/actions/runs/9571801124/job/26389706026).~  We do this very deliberately [here](https://github.com/cmu-delphi/epiprocess/blob/7fd2119d5d116069297e06b70dbf3ff5c08c07bf/R/slide.R#L307) (and probably in an analogous spot for `epix_slide`s); if `f` is missing then `..1` is a tidy computation, not an argument to the computation.  This makes it happen.

Some possible resolutions:
- Pass around nonsense: make the conversion of `..1` to a function (within `as_slide_computation`) take in dots and ignore them, and remove the `... <- missing_arg()` lines.
- Don't pass `...` to `f`: either
  - Disallow using `...` for arg passing, or
  - Make `as_slide_computation` bake any args into `f` if `f` is a function, rather than use `f` as-is (something like `return(function(x,gk,rtv) f(x,gk,rtv,...))`, and no longer pass `...` to computations within the `group_modify` computations of `epi[x]_slide`.  For efficiency's sake, only do this if there are a nonzero number of dots.
  - [^ potentially like the above, but instead of baking args into `f`, have `as_slide_computation()` output both an `f` and a `group_modify_baked()` function that bakes in the dots if appropriate, and use that instead of `group_modify()`.  Perhaps it could actually implement a `baker()` function factory to bake args into whatever function we want, but implementing that might be a bit gnarlier.]

@nmdefries do these sound like solutions?  Any preferences?

**Comment by nmdefries** [comment]
Hm, we've had this warning for a while. I didn't think it was causing CI failures.

What about `assign("...", missing_arg())`?

**Comment by brookslogan** [comment]
That's what I thought, but I didn't originally see any other warnings and Ctrl+F didn't seem to work.  Perhaps the 2 warnings actually were actually "checking for code/documentation mismatches ... WARNING" and "checking Rd \usage sections ... WARNING" from not running document, rather than " Warning: <anonymous>: ... may be used in an incorrect context (/home/runner/work/epiprocess/epiprocess/check/epiprocess.Rcheck/00_pkg_src/epiprocess/R/slide.R:307)" and "Warning: <anonymous>: ... may be used in an incorrect context (/home/runner/work/epiprocess/epiprocess/check/epiprocess.Rcheck/00_pkg_src/epiprocess/R/grouped_epi_archive.R:320)".  CI auto-document didn't trigger a re-check.  Let me try to force one.

`assign` seems like a good hack to test out.

**Comment by brookslogan** [comment]
Okay, looks like it was the lack of document() causing the warnings that actually counted toward that check error.  This is lower priority but probably good to get rid of some check warning spam and any future confusion like mine above.  I'm not 100% sure `assign` does the equivalent things so we'll probably need to test it.
