### ISSUE TITLE
local test failures

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#473]
Tests are passing on CI, but I'm getting lots of local failures which makes the development cycle slow. 

I think they are mostly from `test-epi_slide`. And the main failure mode is using `expect_identical()` rather than `expect_equal()`. Lots of numbers that differ by < 1e-10. See attached output.

[Untitled.md](https://github.com/user-attachments/files/15930227/Untitled.md)

**Comment by dshemetov** [comment]
This appears to be machine-dependent: my Ubuntu machine tests all pass, while on my M3 Mac, the same tests fail, but with slightly different numerical values. I can take a stab at fixing these.

**Comment by dajmcdon** [comment]
Definitely machine dependent. doubles should be tested with `expect_equal()` so that a tolerance can be used. The downside is that the attributes can't be checked simultaneously.
