### ISSUE TITLE
`?epi_df` doesn't pull up help (any more?)

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#493]
[Related:] From a failing check in epipredict:
```
* checking Rd cross-references ... WARNING
Warning: Missing link or links in Rd file 'get_test_data.Rd':
  ‘epi_df’
```
[plus documenting epipredict gives things like
```
✖ arx_forecaster.R:3: @description refers to unavailable topic epiprocess::epi_df.
```
]
Seems likely that users might also try `?epi_df`, so we should make that work (again?).

**Comment by dshemetov** [comment]
This is probably something that got adjusted in #472. I'll take a look.
