### ISSUE TITLE
select.epi_df falls back to tibble if geo_value or time_value are removed

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epiprocess#505]
We should either document this explicitly or error.

```r
r$> epiprocess::jhu_csse_daily_subset %>% select(cases)
# A tibble: 4,026 × 1
   cases
 * <dbl>
 1     6
 2     4
 3     6
 4    11
 5    10
 6    18
 7    26
 8    19
 9    23
10    22
# ℹ 4,016 more rows
# ℹ Use `print(n = ...)` to see more rows
```

**Comment by brookslogan** [comment]
- `dplyr_extending` says decaying is the way you should do it, at least.
- And ideally this would mainly happen when the user doesn't need `epi_df`ness anymore anyway.  One exception before was `.x` fed to a geo-grouped slide computation, but recent slide updates have moved to `.keep = TRUE` so `.x` will now be an `epi_df` there, too.

So seems like explicitly documenting might be the way to go.

**Comment by dshemetov** [comment]
Adding an example to the Getting Started page and in `epi_df` reference page in #538.
