### ISSUE TITLE
Move `prob_arx()` in advanced vignette over to `epipredict`

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/epiprocess#54]
We should move the `prob_arx()` function from the advanced vignette over to the `epipredict`. I moved it over to using list args in preparation for that. And, when the latter package is up and running, we probably just want to call an appropriate forecaster from `epipredict` for the example in the advanced vignette, because that in-vignette definition of `prob_arx()` is kind of unreasonably long and daunting.

**Comment by brookslogan** [comment]
Remaining work here is to use epipredict forecasters in examples, or maybe to simplify `prob_arx` by taking away a bunch of options and using any completion utilities we implement.
