### ISSUE TITLE
Remove dependence on the old covidcast::county_census

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epiprocess#61]
So the only dependency I couldn't remove was `covidcast::county_census` to get all the Massachusetts and Vermont counties. Eventually, we can probably port it over though.

_Originally posted by @dshemetov in https://github.com/cmu-delphi/epiprocess/issues/59#issuecomment-1075385230_

A natural way to do this would be to make this available in the geo aggregation package.

**Comment by dajmcdon** [comment]
Dependency removed by including this data [here](https://github.com/cmu-delphi/epiprocess/blob/e6b7c583989027a5bc8758d386b4e78bf60e7921/data-raw/jhu_csse_county_level_subset.R#L22). But we still have `covidcast` in suggests due to the `data-raw` scripts.
