### ISSUE TITLE
Add option to compactify issue data in `epi_archive`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#62]
`epi_archive`s can be formed based on a conglomeration of full snapshots, issue data with duplicate re-reporting, and/or minimal patch-like issues.  Some space (unsure about time) can be saved by removing rows that match LOCF of previous issues.  Space can be essential if we are attempting in-memory analysis.

Proposal: introduce a constructor argument `compactify`:
- `TRUE`: remove unnecessary rows to give same LOCF results.  Make sure to maintain the same `max_issue` value as the original data.
- `FALSE`: leave data as-is
- default value (say, `NULL`): same as `TRUE` except message the user if this actually changed the data, and telling them how to silence the message

Use cases:
- User inputs full snapshot data, to prevent using space quadratic in the number of snapshots.  (A further enhancement would be to directly work off of a directory of snapshot files or something similar.)
- We are working off of a covidcast data source that historically did not use diff-based issues and/or has many full re-issues.  (E.g., repeating the analysis [here](https://github.com/cmu-delphi/covidcast-indicators/issues/1362) gives covidcast jhu-csse state-level case issue data at 79% duplicates despite the shift to having routine issues being diff-based.  This is still just reducing what `object.size` says is 40MB--50MB down to ~10MB, but at the county level it _might_ matter more.)

**Comment by ryantibs** [comment]
@lcbrooks Thanks for the idea! I think it sounds like a good idea. 

Not sure if `compactify` would be the name I would have come up with. Is that a somewhat commonly-used verb? Or something you made up?

**Comment by brookslogan** [comment]
Regarding the naming: I just didn't want to call it `compress` (this is not applying a general-purpose compression algorithm but something archive-specific) and couldn't think of anything better.  Not sure where I picked up the word, but it's in some dictionaries and appears to be used in math and physics theory in a limited number of contexts.

**Comment by kenmawer** [comment]
I can help with this.

**Comment by brookslogan** [comment]
Is this in a PR already?  If so, could you please point me to it; otherwise, could you open a PR?
