### ISSUE TITLE
Add final newline to epi_archive print statement

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#68]
Currently, epi_archive doesn't print a final newline and leaves the REPL prompt or future output hanging in a weird position.  Add a trailing newline to fix.

**Comment by rachlobay** [comment]
@brookslogan If possible, could you post a screenshot of the problem to help clarify it?

**Comment by brookslogan** [comment]
Reproducing with GitHub Markdown.  Here, `EA` is an `epi_archive`.  `>` is the prompt character.  I've printed 42 twice here to highlight the difference in the prompt placement.
```
> EA
An `epi_archive` object, with metadata:
* geo_type  = state
* time_type = day
----------
* min time value = 2020-01-02
* max time value = 2021-12-31
* min version    = 2020-01-03
* max version    = 2022-03-31
----------
Data archive (stored in DT field): 3285000 x 4
----------
Public methods: initialize, print, as_of, merge, slide, clone> 42
[1] 42
> 42
[1] 42
> 
```

I think the fix is to change `"Public methods: %s"` to `"Public methods: %s\n"`.

(Another `print` wishlist item here: it'd be nice to see all the column names available when printing an `epi_archive` rather than having to print the DT.)

**Comment by rachlobay** [comment]
Great! Thanks for the clarification... I agree with what you're thinking for the fix. I've addressed that and the column names issue wishlist item on Daniel's epiprocess repo.
