### ISSUE TITLE
Add `@examples` throughout package (maybe query-less versions of vignette code)

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#69]
The package currently has a lot of useful vignettes explaining its functionality.  However, at least for Emacs ESS users, `@examples` are a bit more accessible: they pop up within the editor, don't require finding and running a vignette command and finding the output in a browser, allow running within the help window frame, and allow copy-paste with editor navigation shortcuts.  It would be nice to have some of the examples from the vignettes, perhaps with artificial data in place of API downloads, in the roxygen `@examples`.  In some cases, this would also be a step toward #42.

**Comment by ChloeYou** [comment]
@kenmawer @ChloeYou assigned to task

**Comment by kenmawer** [comment]
I'm suggesting that we also have some sort of built-in dataset that can be used for the examples, just like how R has the iris and mtcars datasets that are used for the examples.
