### ISSUE TITLE
Suggest we implement more gh-actions

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#71]
Currently only deploying to gh-pages. I suggest:

1. move `docs/` to the `gh-pages` branch. Rebuild the docs automatically on push/merge.
2. Add gh-actions to run the tests and rebuild the package.
3. Add some branch protection to `main` to prevent push/merge with failing code.

For the automatic rebuilding, we likely should move some of the vignette data (maybe examples too) offline (as suggested in #69). This will generally make R-CMD-Check much faster.

**Comment by dajmcdon** [comment]
@ryantibs @brookslogan Is it alright with you guys if I go ahead and implement this? There is the potential that 2 will run into cmu-delphi/delphi-epidata-r#31

**Comment by ryantibs** [comment]
I'd say go for it---I haven't been following https://github.com/cmu-delphi/delphi-epidata-r/issues/31, so I think you're in a better position to judge this and how likely it is to run into problem, but sounds like you think it's worth it

Apart from #69, worth implementing tests as in #42. I'm not sure where things stand on the testing front, but we should definitely get around to that ...

**Comment by brookslogan** [comment]
So in this case would people `install_github` on `main` or `gh-pages`?  For `install_github` to properly allow people to access `help` functionality, the compiled `man` entries have to already be there AFAIK (see cmu-delphi/delphi-epidata-r#15).  I don't know how vignettes work, though (if they need to be pre-compiled to be accessible when using `install_github` or not).

**Comment by dajmcdon** [comment]
The GitHub pages site is served by the `docs/`, while the help is in `man/`. Currently `docs/` lives on `main`, but we would create an orphan branch called `gh-pages` that contains only `docs/`. Then remove `docs/` from `main`.

On a push to `main`, the action will automatically run `pkgdown` and push the compiled site to the `gh-pages` branch. That way, you never have to rerun locally, and all the of the site documentation won't be on `main`. Running `install_github(cmu-delphi/epiprocess)` would grab `main` and work as expected.

This is actually a common setup. Running `usethis::use_pkgdown_github_pages()` sets it up automatically.
