### ISSUE TITLE
Odd R CMD Check error in `archive` vignette.

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epiprocess#81]
For some reason, my local R CMD Check errors out on `key(x$DT)` around line 90 in this vignette (though no problem when build manually).

Potentially intermittent. 

_Originally posted by @dajmcdon in https://github.com/cmu-delphi/epiprocess/pull/77#discussion_r875280402_

**Comment by dshemetov** [comment]
Closing due to issue age and lack of actionable steps.
