### ISSUE TITLE
Fix some attribution splicing

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#84]
It looks like `archive_cases_dv_subset`, `advanced.Rmd`, `archive.Rmd`, and maybe other locations have an attribution for doctor-visits that got spliced with modification descriptions for jhu-csse.  These should be de-spliced and the missing content added back.

**Comment by brookslogan** [comment]
Spliced versions mix a link to doctor-visits data with a description of JHU-CSSE changes.

```
#' * \href{https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/doctor-visits.html}{From the COVIDcast Epidata Doctor Visits API}: These signals are taken directly from the JHU CSSE \href{https://github.com/CSSEGISandData/COVID-19}{COVID-19 GitHub repository} without changes. The 7-day average signals are computed by Delphi by calculating moving averages of the preceding 7 days, so the signal for June 7 is the average of the underlying data for June 1 through 7, inclusive.
```

```
[From the COVIDcast Epidatab Doctor's Visit API](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/doctor-visits.html): 
 These signals are taken directly from the JHU CSSE [COVID-19 GitHub repository](https://github.com/CSSEGISandData/COVID-19) without changes. 
```

Plus, in context, it looks like some of the doctor-visits attribution has gone missing.

**Comment by ChloeYou** [comment]
For doctor's visit, would the following attribution work?

#' * \href{https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/doctor-visits.html}{From the COVIDcast Doctor Visits API}: These signals are taken directly from the API without changes.
