### ISSUE TITLE
Don't filter by `time_value` in `as_of`

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epiprocess#90]
The current `as_of` includes a time filter relative to the version value.  This prevents us from using `as_of` when storing forecasts in an `epi_archive`.

**Comment by brookslogan** [comment]
Fixing this will likely break arx_forecaster due to a bug there.  I'm writing up some comments and then will open an issue on that other bug.  The other bug will likely need to be resolved first and will block this one.

**Comment by rachlobay** [comment]
@brookslogan To make sure that I understand, is the section that you are referring to lines 216-218  of archive.R?
